#!/usr/bin/env python3
"""D40: calibrate a bounded local-survey admission envelope from frozen receipts."""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent

# These are content pins, not measurements to be regenerated by this program.
INPUTS = {
    "d32": ("fh_l8_local_cost_survey_d32_result.json", "58f4f4acfa2cd0dd095410bbeda374290a6dbf69d86f51f55f89bb286b823b0e"),
    "d33": ("fh_l8_local_cost_survey_replay_d33_result.json", "99b3b8149012e2b0fe4e9edc65aa93987f5c43432782163bab7f18a5030becec"),
    "d35": ("fh_l8_local_cost_survey_d35_result.json", "ba9b246060cbca57eb5bd2442a9fcc6b993a069bdee253b06696e9bcd7c8587d"),
    "d36": ("fh_l8_local_cost_survey_replay_d36_result.json", "a313f57b2cf703f4fcecb23998a2e56f6a70fcb7d16cfd8a0800a684dce99d18"),
    "d38": ("fh_l8_local_cost_survey_d38_result.json", "3ea20596cf864c2c8d66a5f99d633785a2a845fe6e9b0aad4d8c7ce5de352a78"),
    "d39": ("fh_l8_local_cost_survey_replay_d39_result.json", "f129a19838bb85e195ff6ac9ad987aa60008f28ed4e4274f01e6cb5e75f99702"),
}


def _read_inputs():
    values = {}
    for label, (name, expected_sha) in INPUTS.items():
        raw = (HERE / name).read_bytes()
        actual_sha = hashlib.sha256(raw).hexdigest()
        if actual_sha != expected_sha:
            raise RuntimeError(f"input pin mismatch: {label}")
        values[label] = json.loads(raw)
    return values


def run():
    x = _read_inputs()
    structural_replays = (
        x["d33"]["rows_match"]
        and x["d36"]["rows_match"]
        and x["d39"]["structural_rows_match"]
    )
    if not structural_replays:
        raise RuntimeError("a local scale lacks a structural replay")
    scales = (x["d32"], x["d35"], x["d38"])
    replays = (x["d33"], x["d36"], x["d39"])
    if any(v["packed_q3_reads"] != 0 for v in (*scales, *replays)):
        raise RuntimeError("local envelope forbids packed-q3 reads")
    if any(v["full_53_scientific_execution_authorized"] for v in (*scales, *replays)):
        raise RuntimeError("local envelope does not authorize full-53")
    observed_rss = [v["process_peak_rss_kib"] for v in scales]
    observed_rss += [v[f"d{a}_peak_rss_kib"] for v, a in zip(replays, (32, 35, 38))]
    # A fixed, deliberately slack local admission cap: 64 MiB, not an extrapolation.
    # It is a safety/operational criterion for one future bounded experiment only.
    return {
        "status": "VERIFIED_D40_BOUNDED_LOCAL_COST_ENVELOPE",
        "input_sha256": {label: sha for label, (_, sha) in INPUTS.items()},
        "verified_scales": [8, 16, 32],
        "structural_replays_verified": True,
        "observed_peak_rss_kib_min": min(observed_rss),
        "observed_peak_rss_kib_max": max(observed_rss),
        "next_bounded_survey": {
            "representatives": 64,
            "max_selection_collector_calls": 3,
            "max_scientific_action_calls": 68,
            "admission_rss_cap_kib": 65536,
            "require_independent_structural_replay": True,
            "require_packed_q3_reads": 0,
        },
        "packed_q3_reads": 0,
        "full_53_scientific_execution_authorized": False,
        "full53_extrapolation_forbidden": True,
        "next_gate": "BOUNDED_SCALE64_SURVEY_WITHIN_D40_PRECOMMITTED_ENVELOPE",
    }


if __name__ == "__main__":
    print(json.dumps(run(), sort_keys=True, separators=(",", ":")))
