#!/usr/bin/env bash
set -euo pipefail
PATH=/usr/bin:/bin;export PATH LC_ALL=C TZ=UTC PYTHONDONTWRITEBYTECODE=1 PYTHONNOUSERSITE=1 PYTHONSAFEPATH=1
fail(){ printf 'T18 verifier gate failed: %s\n' "$*" >&2;exit 1; };tier="${1:-full-replay}";case "$tier" in fast|full-replay);;*)fail tier;;esac
cd "$(dirname "${BASH_SOURCE[0]}")/..";base=63e3fd35ddf4efbc09dd96c6f58df2fa8935c4e9;stem=biocortex_ab_track_b_reference_provider_fault_injection_runner_reviewer_independence_synthetic_exact_t17_receipt_track_and_validator_build_config_binding_verifier_isolated_lab_v1
paths=("docs/reports/goal-c-u/2026-07-20-biocortex-track-b-reference-provider-fault-injection-runner-reviewer-independence-synthetic-exact-t17-receipt-track-and-validator-build-config-binding-verifier-isolated-lab-v1-pack.md" "scripts/check-biocortex-ab-track-b-reference-provider-fault-injection-runner-reviewer-independence-synthetic-exact-t17-receipt-track-and-validator-build-config-binding-verifier-isolated-lab-v1-pack.sh" "scripts/eval/${stem}.py" "scripts/eval/check_${stem}_pack.py" "scripts/eval/fixtures/${stem}_pack.expected.v0.tsv" "scripts/eval/fixtures/${stem}_pack_v0.json");modes=(100644 100755 100644 100644 100644 100644)
[[ -z "$(git status --porcelain --untracked-files=all)" ]]||fail dirty;read -r -a l<<<"$(git rev-list --parents -n1 HEAD)";p=("${l[@]:1}");if [[ ${#p[@]} == 1 && "${p[0]}" == "$base" ]];then mode=source;src=HEAD;elif [[ ${#p[@]} == 2 ]];then mode=integrated;src="${p[1]}";else fail topology;fi;[[ "$tier" != full-replay || "$mode" == integrated ]]||fail full
tmp=$(mktemp -d);trap 'rm -rf "$tmp"' EXIT;for x in "${paths[@]}";do printf 'A\t%s\n' "$x";done|sort>"$tmp/w";git diff-tree --no-commit-id --name-status -r "$base" "$src"|sort>"$tmp/a";cmp -s "$tmp/w" "$tmp/a"||fail delta
for i in "${!paths[@]}";do read -r m _ _ x< <(git ls-files --stage -- "${paths[$i]}");[[ "$m" == "${modes[$i]}" && "$x" == "${paths[$i]}" ]]||fail path;done
python3 "scripts/eval/check_${stem}_pack.py">"$tmp/o";cmp -s "scripts/eval/fixtures/${stem}_pack.expected.v0.tsv" "$tmp/o"||fail expected;python3 "scripts/eval/check_${stem}_pack.py" --self-test|grep -qx $'self_test_boundary\tpass'||fail selftest
printf 't18_review_independence_verifier_gate\tpass\nvalidation_tier\t%s\nrelease_topology\t%s\npacket_path_count\t6\npredecessor_review_count_per_case\t1\nimplementation_authority_single_use_consumed\ttrue\nisolated_lab_candidate_surface_component_total\t16\nt19_authorized\tfalse\n' "$tier" "$mode"
