#!/usr/bin/env bash
set -euo pipefail
PATH=/usr/bin:/bin;export PATH LC_ALL=C TZ=UTC PYTHONDONTWRITEBYTECODE=1
tier="${1:-full-replay}";[[ "$tier" == fast || "$tier" == full-replay ]]||exit 1;cd "$(dirname "${BASH_SOURCE[0]}")/..";base=514aff86488c13c695709ef474d4b67b87887fe7;stem=biocortex_ab_track_b_reference_provider_fault_injection_runner_premature_authority_synthetic_exact_t19_receipt_track_and_control_evidence_decision_downstream_separation_verifier_isolated_lab_v1
paths=(docs/reports/goal-c-u/2026-07-20-biocortex-track-b-reference-provider-fault-injection-runner-premature-authority-synthetic-exact-t19-receipt-track-and-control-evidence-decision-downstream-separation-verifier-isolated-lab-v1-pack.md scripts/check-biocortex-ab-track-b-reference-provider-fault-injection-runner-premature-authority-synthetic-exact-t19-receipt-track-and-control-evidence-decision-downstream-separation-verifier-isolated-lab-v1-pack.sh scripts/eval/${stem}.py scripts/eval/check_${stem}_pack.py scripts/eval/fixtures/${stem}_pack.expected.v0.tsv scripts/eval/fixtures/${stem}_pack_v0.json);modes=(100644 100755 100644 100644 100644 100644)
[[ -z "$(git status --porcelain --untracked-files=all)" ]]||exit 1;read -r -a l<<<"$(git rev-list --parents -n1 HEAD)";p=("${l[@]:1}");if [[ ${#p[@]} == 1 && "${p[0]}" == "$base" ]];then mode=source;src=HEAD;elif [[ ${#p[@]} == 2 ]];then mode=integrated;src="${p[1]}";else exit 1;fi;[[ "$tier" != full-replay || "$mode" == integrated ]]||exit 1
tmp=$(mktemp -d);trap 'rm -rf "$tmp"' EXIT;for x in "${paths[@]}";do printf 'A\t%s\n' "$x";done|sort>"$tmp/w";git diff-tree --no-commit-id --name-status -r "$base" "$src"|sort>"$tmp/a";cmp -s "$tmp/w" "$tmp/a"||exit 1;for i in "${!paths[@]}";do read -r m _ _ x< <(git ls-files --stage -- "${paths[$i]}");[[ "$m" == "${modes[$i]}" && "$x" == "${paths[$i]}" ]]||exit 1;done
python3 scripts/eval/check_${stem}_pack.py>"$tmp/o";cmp -s scripts/eval/fixtures/${stem}_pack.expected.v0.tsv "$tmp/o"||exit 1;python3 scripts/eval/check_${stem}_pack.py --self-test|grep -qx $'self_test_boundary\tpass'||exit 1
printf 't20_premature_authority_verifier_gate\tpass\nvalidation_tier\t%s\nrelease_topology\t%s\npacket_path_count\t6\npredecessor_review_count_per_case\t1\nstatus\tREJECTED_FAIL_CLOSED\npositive_production_decision\tfalse\ndownstream_execution_authority\tfalse\nsuccessor_authorized\tfalse\n' "$tier" "$mode"
