#!/usr/bin/env bash
set -euo pipefail
PATH=/usr/bin:/bin;export PATH LC_ALL=C TZ=UTC PYTHONDONTWRITEBYTECODE=1
fail(){ exit 1; };tier="${1:-full-replay}";[[ "$tier" == fast || "$tier" == full-replay ]]||fail;cd "$(dirname "${BASH_SOURCE[0]}")/..";base=47c9c21ed35a17037102731bcf1f865774f668db;stem=biocortex_ab_track_b_reference_provider_fault_injection_runner_owner_identity_window_isolated_lab_implementation_authority_and_resource_binding_decision_v1_pack
paths=(docs/reports/goal-c-u/2026-07-20-biocortex-track-b-reference-provider-fault-injection-runner-owner-identity-window-isolated-lab-implementation-authority-and-resource-binding-decision-v1-pack.md scripts/check-biocortex-ab-track-b-reference-provider-fault-injection-runner-owner-identity-window-isolated-lab-implementation-authority-and-resource-binding-decision-v1-pack.sh scripts/eval/${stem%_pack}.py scripts/eval/check_${stem}.py scripts/eval/fixtures/${stem}.expected.v0.tsv scripts/eval/fixtures/${stem}_owner_decision_v0.json scripts/eval/fixtures/${stem}_v0.json);modes=(100644 100755 100644 100644 100644 100644 100644)
[[ -z "$(git status --porcelain --untracked-files=all)" ]]||fail;read -r -a l<<<"$(git rev-list --parents -n1 HEAD)";p=("${l[@]:1}");if [[ ${#p[@]} == 1 && "${p[0]}" == "$base" ]];then mode=source;src=HEAD;elif [[ ${#p[@]} == 2 ]];then mode=integrated;src="${p[1]}";else fail;fi;[[ "$tier" != full-replay || "$mode" == integrated ]]||fail
tmp=$(mktemp -d);trap 'rm -rf "$tmp"' EXIT;for x in "${paths[@]}";do printf 'A\t%s\n' "$x";done|sort>"$tmp/w";git diff-tree --no-commit-id --name-status -r "$base" "$src"|sort>"$tmp/a";cmp -s "$tmp/w" "$tmp/a"||fail;for i in "${!paths[@]}";do read -r m _ _ x< <(git ls-files --stage -- "${paths[$i]}");[[ "$m" == "${modes[$i]}" && "$x" == "${paths[$i]}" ]]||fail;done
python3 scripts/eval/check_${stem}.py>"$tmp/o";cmp -s scripts/eval/fixtures/${stem}.expected.v0.tsv "$tmp/o"||fail;python3 scripts/eval/check_${stem}.py --self-test|grep -qx $'self_test_boundary\tpass'||fail
printf 't19_owner_identity_window_authority_gate\tpass\nvalidation_tier\t%s\nrelease_topology\t%s\npacket_path_count\t7\ndecision_implements_components\t0\ndecision_consumes_authority\tfalse\n' "$tier" "$mode"
