#!/usr/bin/env bash
set -euo pipefail
PATH=/usr/bin:/bin;export PATH LC_ALL=C TZ=UTC PYTHONDONTWRITEBYTECODE=1
tier="${1:-full-replay}";[[ "$tier" == fast || "$tier" == full-replay ]]||exit 1;cd "$(dirname "${BASH_SOURCE[0]}")/..";base=b3264fcf3727f7380165eb8de43b76d65b6b2e73;stem=biocortex_ab_track_b_reference_provider_fault_injection_runner_decision_downstream_separation_isolated_lab_implementation_authority_and_resource_binding_decision_v1_pack
paths=(docs/reports/goal-c-u/2026-07-20-biocortex-track-b-reference-provider-fault-injection-runner-decision-downstream-separation-isolated-lab-implementation-authority-and-resource-binding-decision-v1-pack.md scripts/check-biocortex-ab-track-b-reference-provider-fault-injection-runner-decision-downstream-separation-isolated-lab-implementation-authority-and-resource-binding-decision-v1-pack.sh scripts/eval/${stem%_pack}.py scripts/eval/check_${stem}.py scripts/eval/fixtures/${stem}.expected.v0.tsv scripts/eval/fixtures/${stem}_owner_decision_v0.json scripts/eval/fixtures/${stem}_v0.json);modes=(100644 100755 100644 100644 100644 100644 100644)
[[ -z "$(git status --porcelain --untracked-files=all)" ]]||exit 1;read -r -a l<<<"$(git rev-list --parents -n1 HEAD)";p=("${l[@]:1}");if [[ ${#p[@]} == 1 && "${p[0]}" == "$base" ]];then mode=source;src=HEAD;elif [[ ${#p[@]} == 2 ]];then mode=integrated;src="${p[1]}";else exit 1;fi;[[ "$tier" != full-replay || "$mode" == integrated ]]||exit 1
tmp=$(mktemp -d);trap 'rm -rf "$tmp"' EXIT;for x in "${paths[@]}";do printf 'A\t%s\n' "$x";done|sort>"$tmp/w";git diff-tree --no-commit-id --name-status -r "$base" "$src"|sort>"$tmp/a";cmp -s "$tmp/w" "$tmp/a"||exit 1;for i in "${!paths[@]}";do read -r m _ _ x< <(git ls-files --stage -- "${paths[$i]}");[[ "$m" == "${modes[$i]}" && "$x" == "${paths[$i]}" ]]||exit 1;done
python3 scripts/eval/check_${stem}.py>"$tmp/o";cmp -s scripts/eval/fixtures/${stem}.expected.v0.tsv "$tmp/o"||exit 1;python3 scripts/eval/check_${stem}.py --self-test|grep -qx $'self_test_boundary\tpass'||exit 1
printf 't20_premature_authority_gate\tpass\nvalidation_tier\t%s\nrelease_topology\t%s\npacket_path_count\t7\ndecision_implements_components\t0\ndecision_consumes_authority\tfalse\npositive_production_decision\tfalse\ndownstream_execution_authority\tfalse\n' "$tier" "$mode"
