#!/usr/bin/env bash
set -euo pipefail
PATH=/usr/bin:/bin;export PATH LC_ALL=C TZ=UTC PYTHONDONTWRITEBYTECODE=1
tier="${1:-full-replay}";[[ "$tier" == fast || "$tier" == full-replay ]]||exit 1;cd "$(dirname "${BASH_SOURCE[0]}")/..";base=b23f72332a49131abec1c2d05dcd723134ca19ba;stem=biocortex_ab_track_b_reference_provider_fault_injection_runner_owner_identity_window_synthetic_exact_t18_receipt_track_and_owner_role_signature_same_set_revision_deadline_binding_verifier_isolated_lab_v1
paths=(docs/reports/goal-c-u/2026-07-20-biocortex-track-b-reference-provider-fault-injection-runner-owner-identity-window-synthetic-exact-t18-receipt-track-and-owner-role-signature-same-set-revision-deadline-binding-verifier-isolated-lab-v1-pack.md scripts/check-biocortex-ab-track-b-reference-provider-fault-injection-runner-owner-identity-window-synthetic-exact-t18-receipt-track-and-owner-role-signature-same-set-revision-deadline-binding-verifier-isolated-lab-v1-pack.sh scripts/eval/${stem}.py scripts/eval/check_${stem}_pack.py scripts/eval/fixtures/${stem}_pack.expected.v0.tsv scripts/eval/fixtures/${stem}_pack_v0.json);modes=(100644 100755 100644 100644 100644 100644)
[[ -z "$(git status --porcelain --untracked-files=all)" ]]||exit 1;read -r -a l<<<"$(git rev-list --parents -n1 HEAD)";p=("${l[@]:1}");if [[ ${#p[@]} == 1 && "${p[0]}" == "$base" ]];then mode=source;src=HEAD;elif [[ ${#p[@]} == 2 ]];then mode=integrated;src="${p[1]}";else exit 1;fi;[[ "$tier" != full-replay || "$mode" == integrated ]]||exit 1
tmp=$(mktemp -d);trap 'rm -rf "$tmp"' EXIT;for x in "${paths[@]}";do printf 'A\t%s\n' "$x";done|sort>"$tmp/w";git diff-tree --no-commit-id --name-status -r "$base" "$src"|sort>"$tmp/a";cmp -s "$tmp/w" "$tmp/a"||exit 1;for i in "${!paths[@]}";do read -r m _ _ x< <(git ls-files --stage -- "${paths[$i]}");[[ "$m" == "${modes[$i]}" && "$x" == "${paths[$i]}" ]]||exit 1;done
python3 scripts/eval/check_${stem}_pack.py>"$tmp/o";cmp -s scripts/eval/fixtures/${stem}_pack.expected.v0.tsv "$tmp/o"||exit 1;python3 scripts/eval/check_${stem}_pack.py --self-test|grep -qx $'self_test_boundary\tpass'||exit 1
printf 't19_owner_identity_window_verifier_gate\tpass\nvalidation_tier\t%s\nrelease_topology\t%s\npacket_path_count\t6\npredecessor_review_count_per_case\t1\nimplementation_authority_single_use_consumed\ttrue\nisolated_lab_candidate_surface_component_total\t17\nt20_authorized\tfalse\n' "$tier" "$mode"
